const SynchronizerTypes = {
    ADD_QUE:"ADD_QUE",
    PUSH_QUE_START:"PUSH_QUE_START",
    PUSH_QUE:"PUSH_QUE",
    DIGEST_QUE:"DIGEST_QUE",
    RELEASE_QUE_START:"RELEASE_QUE_START",
    RELEASE_QUE:"RELEASE_QUE",
    SET_QUE_START:"SET_QUE_START",
    SET_QUE:"SET_QUE",
    SET_PLAYER_PATH_START:"SET_PLAYER_PATH_START"
}

export default SynchronizerTypes